name: Build and Package Blocky

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x' # change if needed

      - name: Restore dependencies
        run: dotnet restore Blocky.sln

      - name: Publish (self-contained, win-x64)
        run: dotnet publish Blocky/Blocky.csproj -c Release -r win-x64 --self-contained true -o ./publish

      - name: Zip build output
        run: Compress-Archive -Path ./publish/* -DestinationPath ./blocky.zip

      - name: Upload release artifact
        uses: softprops/action-gh-release@v1
        with:
          files: ./blocky.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
